type = "file"
name = "Glimpse"
capacities = [ 250, 500, 750, 1000, 1250, 1500, 1750, 2000 ]
caches = [
    "otter",
    "theine",
    "ristretto",
    "sturdyc",
    "arc",
    "lru",
]

[file]
trace_type = "lirs"
paths = [ "trace/lirs/gli.gz" ]
