type = "file"
name = "P8lol"
capacities = [ 10_000, 20_000, 30_000, 40_000, 50_000, 60_000, 70_000, 80_000 ]
caches = [
    "otter",
    "theine",
    "ristretto",
    "sturdyc",
    "arc",
    "lru",
]

[file]
paths = [
    { trace_type = "arc", path = "trace/arc/p8.gz" },
]