name: Test 32-bit arch

on:
  push:
    paths-ignore:
      - docs/**

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.24.x ]

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test 32-bit arch
        run: make test.32-bit
