name: Test

on: [push]

jobs:
  test-windows:
    strategy:
      matrix:
        go-version: [ 1.19.x, 1.22.x ]

    runs-on: windows-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Unit tests
        run: make test.unit
